# Generated by Django 5.2.1 on 2025-06-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
    ]
