# Generated by Django 5.2.1 on 2025-06-22 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_rename_postimages_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, underscores, and spaces.', regex='^[\\w ]+$')]),
        ),
    ]
