# Generated by Django 5.2.1 on 2025-06-26 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspace',
            name='donate_page_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventspace',
            name='donate_page_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='DonationFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=55)),
                ('card_description', models.CharField(blank=True, max_length=255, null=True)),
                ('card_cover_image', models.ImageField(blank=True, null=True, upload_to='donation_covers/')),
                ('card_venmo_link', models.URLField(blank=True)),
                ('card_dono_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_funds', to=settings.AUTH_USER_MODEL)),
                ('event_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_funds', to='spaces.eventspace')),
            ],
        ),
    ]
