# Generated by Django 5.2.1 on 2025-06-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_eventspace_donate_page_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationfund',
            name='card_cover_image',
        ),
        migrations.AddField(
            model_name='donationfund',
            name='original_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='donation_covers/'),
        ),
    ]
