# Generated by Django 5.2.1 on 2025-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_remove_donationfund_card_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.AddField(
            model_name='postimage',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
