# Generated by Django 5.2.1 on 2025-06-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_remove_postimage_image_postimage_original_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventspace',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='eventspace',
            name='original_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='space_covers/'),
        ),
    ]
