# Generated by Django 5.2.1 on 2025-06-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_remove_eventspace_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
